import Head from 'next/head';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';

type Props = {
  refreshUserProfile: () => Promise<void>;
};
export default function Home(props: Props) {
  console.log("index props: ", props)
  const refreshUserProfile = props.refreshUserProfile
  useEffect(() => {
    refreshUserProfile()
      .catch(() => console.log('refresh user profile failed'));
  }, [refreshUserProfile]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
