/** @jsxImportSource @emotion/react */

import { Button, Typography } from '@mui/material';
import Head from 'next/head';
import { useEffect } from 'react';
import { landingPageBackground } from '../styles/customStyles';

type Props = {
  refreshUserProfile: () => Promise<void>;
};
export default function Home(props: Props) {
  console.log('index props: ', props);
  const refreshUserProfile = props.refreshUserProfile;
  useEffect(() => {
    refreshUserProfile().catch(() =>
      console.log('refresh user profile failed'),
    );
  }, [refreshUserProfile]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={landingPageBackground}>
        <div className="background">
          <div className="hero">
            <Typography
              variant="h1"
              sx={{ fontFamily: 'monospace', fontWeight: 400, fontSize: 64 }}
            >
              Δelphi
            </Typography>
            <Typography
              variant="h4"
              sx={{
                fontFamily: 'monospace',
                fontWeight: 400,
                fontSize: 36,
                mt: 0,
                mb: '50px',
              }}
            >
              Your fact check assistant
            </Typography>
            <Button variant="contained" color="secondary" href="/register">
              Sign up
            </Button>
          </div>
          <div className="teaser">
            <Typography sx={{ mb: "20px", fontSize: 20}}>
              Search and evaluate any given claim on the basis of various
              sources.
            </Typography>
            <Typography sx={{ mb: "20px", fontSize: 20}}>
              Access our database and contribute your own claims and reviews.
            </Typography>
          </div>
        </div>
      </main>
    </>
  );
}
