name: Playwright Tests
on: push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    # Update env variables with your own database credentials
    env:
      PGHOST: ${{ secrets.PGHOST }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSERNAME: ${{ secrets.PGUSERNAME }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}

    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database
        run: |
          sudo -u postgres psql --command='CREATE DATABASE $PGDATABASE;'
      - name: Create user
        run: |
          sudo -u postgres psql --command="CREATE USER $PGUSERNAME WITH ENCRYPTED PASSWORD '$PGPASSWORD';"
      - name: Create privileges
        run: |
          sudo -u postgres psql --command="GRANT ALL PRIVILEGES ON DATABASE $PGDATABASE TO $PGUSERNAME;"
      - name: Add user
        run: |
          sudo adduser $PGUSERNAME
      - uses: actions/checkout@v2
      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: yarn playwright install-deps
      - run: yarn migrate up
      - name: Build localhost
        run: yarn build
      - name: Run tests
        run: yarn playwright test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-screenshots-videos
          path: test-results/